- project:
    check:
      jobs:
        # This is part of our job template. We'll remove it when all our
        # python projects are py3x ready
        - tox-py27:
            voting: false
        - tox-py36:
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-ubi7
            voting: true
        - tox-pep8-py36:
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-ubi7
            voting: true
    gate:
      jobs:
        # This is part of our job template. We'll remove it when all our
        # python projects are py3x ready
        - tox-py27:
            voting: false
        - tox-py36:
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-ubi7
            voting: true
        - tox-pep8-py36:
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-ubi7
            voting: true
    release:
      jobs:
        - upload-pypi
