- project:
    check:
      jobs:
        # This is part of our job template. We'll remove it when all our
        # python projects are py3x ready
        - tox-py27:
            voting: false
        - tox-py36:
            pre-run:
              - playbooks/prepare-host.yaml
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-f37
            voting: true
        - tox-pep8-py36:
            pre-run:
              - playbooks/prepare-host.yaml
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-f37
            voting: true
    gate:
      jobs:
        # This is part of our job template. We'll remove it when all our
        # python projects are py3x ready
        - tox-py27:
            voting: false
        - tox-py36:
            pre-run:
              - playbooks/prepare-host.yaml
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-f37
            voting: true
        - tox-pep8-py36:
            pre-run:
              - playbooks/prepare-host.yaml
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-f37
            voting: true
    release:
      jobs:
        - upload-pypi
