---
- name: Install required packages
  hosts: all
  tasks:
    - name: Install python3.6 and gcc packages
      become: true
      package:
        name:
          - python3.6
          - gcc
        state: present
